typography_spectrum: 0.54261
color:
  brandColors:
    - '#683f5f'
    - '#b2b379'
    - '#461645'
    - '#b7e0af'
    - '#e9fdd4'
  brandStrength: 0.375
  lightness: 0.375
  saturation: 0.375
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.14301
analytics:
  google: null
  facebook: null
  twitter: null
name: stabshadow
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: STABSHADOW DESIGN
description: testing
purpose: []
