name: stabshadow
favicon: null
layout_spectrum: 0
typography_spectrum: 0.54261
title: STABSHADOW DESIGN
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#693e60'
    - '#b0ae72'
    - '#afd8a2'
    - '#491648'
    - '#8f8a6e'
  brandStrength: 0.8125
  lightness: 0.625
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
