name: stabshadow
favicon: null
layout_spectrum: 0.70155
typography_spectrum: 0.54261
title: STABSHADOW DESIGN
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#683f5f'
    - '#b2b379'
    - '#461645'
    - '#b7e0af'
    - '#e9fdd4'
  brandStrength: 0.75
  lightness: 0.5
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
