name: stabshadow
favicon: null
layout_spectrum: 0
typography_spectrum: 0.54261
title: STABSHADOW DESIGN
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c6c6c6'
    - '#565757'
    - '#5cbe80'
    - '#ae1f23'
    - '#bd898b'
  brandStrength: 0.4375
  lightness: 0.75
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
