name: stabshadow
favicon: null
layout_spectrum: 0.24004
typography_spectrum: 0.5632953136228025
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.4375
  lightness: 0.6753174106124789
  saturation: 0.9771403474733233
  rhythmicContrast: 0.23132964689284563
purpose: []
